package compilador.unitri.sintatico;

public enum TipoNo {

    NO_LISTDEF,
    NO_DEF,
    NO_LISTPARAM,
    NO_LISTPARAM2,
    NO_PARAM,
    NO_TIPO,
    NO_LISTCOMAN,
    NO_COMAN,
    NO_DECL,
    NO_LISTID,
    NO_LISTID2,
    NO_ATRIB,
    NO_EXPREARIT,
    NO_EXPRARIT2,
    NO_TERMO,
    NO_TERMO2,
    NO_FATOR,
    NO_OPERANDO,
    NO_OP1,
    NO_OP2,
    NO_OP3,
    NO_LACO,
    NO_EXPREL,
    NO_SE,
    NO_SENAO,
    NO_RET,
    NO_ENTRADA,
    NO_SAIDA,
    NO_CHAMADA,
    NO_LISTARG,
    NO_LISTARG2,
    NO_TOKEN
}
